"""Conversation state in SQLite: conversations, messages, runs, and human-approval requests."""

from __future__ import annotations

import json
import sqlite3
import uuid
from contextlib import closing
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

SCHEMA = """
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    run_id TEXT,
    message TEXT NOT NULL,              -- the full chat message as JSON (audit trail)
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    question TEXT NOT NULL,
    status TEXT NOT NULL,               -- running | completed | stopped | failed
    stop_reason TEXT,
    answer TEXT,                        -- final structured answer as JSON
    usage TEXT,                         -- steps, tool calls, tokens, latency as JSON
    started_at TEXT NOT NULL,
    finished_at TEXT
);
CREATE TABLE IF NOT EXISTS approvals (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES runs(id),
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    tool TEXT NOT NULL,
    arguments TEXT NOT NULL,            -- exactly what will run if approved (never re-generated by the model)
    risk_notes TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'denied')),
    reviewer TEXT,
    result TEXT,
    created_at TEXT NOT NULL,
    decided_at TEXT
);
"""


class ApprovalConflict(Exception):
    """The approval was already decided (approve/deny happens at most once)."""


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


class StateStore:
    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with closing(self._connect()) as con, con:
            con.execute("PRAGMA journal_mode=WAL")  # readers don't block the writer (API + evaluation at the same time)
            con.executescript(SCHEMA)

    def _connect(self) -> sqlite3.Connection:
        con = sqlite3.connect(self.path, timeout=30)
        con.row_factory = sqlite3.Row
        return con

    # ---------------------------------------------------------------- conversations and messages
    def ensure_conversation(self, conversation_id: str | None = None) -> str:
        conversation_id = conversation_id or uuid.uuid4().hex
        with closing(self._connect()) as con, con:
            con.execute("INSERT OR IGNORE INTO conversations (id, created_at) VALUES (?, ?)", (conversation_id, _now()))
        return conversation_id

    def conversation_exists(self, conversation_id: str) -> bool:
        with closing(self._connect()) as con:
            return con.execute("SELECT 1 FROM conversations WHERE id = ?", (conversation_id,)).fetchone() is not None

    def add_message(self, conversation_id: str, run_id: str | None, message: dict) -> None:
        with closing(self._connect()) as con, con:
            con.execute("INSERT INTO messages (conversation_id, run_id, message, created_at) VALUES (?, ?, ?, ?)",
                        (conversation_id, run_id, json.dumps(message, ensure_ascii=False), _now()))

    def messages(self, conversation_id: str) -> list[dict]:
        with closing(self._connect()) as con:
            rows = con.execute("SELECT run_id, message, created_at FROM messages WHERE conversation_id = ? ORDER BY id",
                               (conversation_id,)).fetchall()
        return [{"run_id": r["run_id"], "created_at": r["created_at"], **json.loads(r["message"])} for r in rows]

    def history(self, conversation_id: str, max_turns: int = 3) -> list[dict]:
        """Compact memory for the next run: the last completed question/answer pairs (no tool chatter)."""
        with closing(self._connect()) as con:
            rows = con.execute("SELECT question, answer FROM runs WHERE conversation_id = ? AND status = 'completed' "
                               "ORDER BY started_at DESC, rowid DESC LIMIT ?", (conversation_id, max_turns)).fetchall()
        turns = []
        for row in reversed(rows):
            answer = json.loads(row["answer"] or "{}")
            turns += [{"role": "user", "content": row["question"]},
                      {"role": "assistant", "content": answer.get("answer", "")}]
        return turns

    # ---------------------------------------------------------------- runs
    def start_run(self, run_id: str, conversation_id: str, question: str) -> None:
        with closing(self._connect()) as con, con:
            con.execute("INSERT INTO runs (id, conversation_id, question, status, started_at) VALUES (?, ?, ?, 'running', ?)",
                        (run_id, conversation_id, question, _now()))

    def finish_run(self, run_id: str, *, status: str, stop_reason: str, answer: dict | None, usage: dict) -> None:
        with closing(self._connect()) as con, con:
            con.execute("UPDATE runs SET status = ?, stop_reason = ?, answer = ?, usage = ?, finished_at = ? WHERE id = ?",
                        (status, stop_reason, json.dumps(answer) if answer is not None else None, json.dumps(usage), _now(), run_id))

    def get_run(self, run_id: str) -> dict | None:
        with closing(self._connect()) as con:
            row = con.execute("SELECT * FROM runs WHERE id = ?", (run_id,)).fetchone()
        if row is None:
            return None
        record = dict(row)
        for key in ("answer", "usage"):
            record[key] = json.loads(record[key]) if record[key] else None
        return record

    def runs(self, conversation_id: str) -> list[dict]:
        with closing(self._connect()) as con:
            ids = [r[0] for r in con.execute("SELECT id FROM runs WHERE conversation_id = ? ORDER BY started_at, rowid", (conversation_id,))]
        return [self.get_run(i) for i in ids]

    # ---------------------------------------------------------------- approvals
    def create_approval(self, run_id: str, conversation_id: str, tool: str, arguments: dict[str, Any], risk_notes: list[str]) -> dict:
        approval_id = uuid.uuid4().hex[:16]
        with closing(self._connect()) as con, con:
            con.execute("INSERT INTO approvals (id, run_id, conversation_id, tool, arguments, risk_notes, status, created_at) "
                        "VALUES (?, ?, ?, ?, ?, ?, 'pending', ?)",
                        (approval_id, run_id, conversation_id, tool, json.dumps(arguments, ensure_ascii=False), json.dumps(risk_notes), _now()))
        return self.get_approval(approval_id)

    def get_approval(self, approval_id: str) -> dict | None:
        with closing(self._connect()) as con:
            row = con.execute("SELECT * FROM approvals WHERE id = ?", (approval_id,)).fetchone()
        return self._approval(row) if row else None

    def list_approvals(self, status: str | None = None) -> list[dict]:
        with closing(self._connect()) as con:
            rows = con.execute("SELECT * FROM approvals WHERE (? IS NULL OR status = ?) ORDER BY created_at, rowid", (status, status)).fetchall()
        return [self._approval(r) for r in rows]

    def decide_approval(self, approval_id: str, *, approved: bool, reviewer: str) -> dict:
        """Atomic pending -> approved/denied. A second decision raises ApprovalConflict, so an action can't run twice."""
        with closing(self._connect()) as con, con:
            cursor = con.execute("UPDATE approvals SET status = ?, reviewer = ?, decided_at = ? WHERE id = ? AND status = 'pending'",
                                 ("approved" if approved else "denied", reviewer, _now(), approval_id))
        if cursor.rowcount == 0:
            existing = self.get_approval(approval_id)
            if existing is None:
                raise KeyError(approval_id)
            raise ApprovalConflict(f"approval {approval_id} is already {existing['status']}")
        return self.get_approval(approval_id)

    def set_approval_result(self, approval_id: str, result: dict) -> None:
        with closing(self._connect()) as con, con:
            con.execute("UPDATE approvals SET result = ? WHERE id = ?", (json.dumps(result, ensure_ascii=False, default=str), approval_id))

    @staticmethod
    def _approval(row: sqlite3.Row) -> dict:
        record = dict(row)
        record["arguments"] = json.loads(record["arguments"])
        record["risk_notes"] = json.loads(record["risk_notes"])
        record["result"] = json.loads(record["result"]) if record["result"] else None
        return record
